Deprecates `actfw` package in favor of `actfw-core` and `actfw-raspberrypi`, keeping forward compatibility
Idein/actcast-app-python pull request #40
Opened 2020-12-17 23:05 UTC by laysakura

TODO

- how to test
- `pipenv install --pre --dev -e .`

2020-12-21 01:54 UTC, notogawa requested changes
It is better to display a deprecation warning if a user imports actfw.

2020-12-21 01:54 UTC, notogawa commented on actfw/application/__init__.py
> +from actfw_core.application import *
```suggestion
from actfw_core.application import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/capture/__init__.py
> +from actfw_raspberrypi.capture import *
```suggestion
from actfw_core.capture import *
from actfw_raspberrypi.capture import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core and actfw-raspberrypi instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/command_server/__init__.py
> +from actfw_core.command_server import *
```suggestion
from actfw_core.command_server import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/display/__init__.py
> +from actfw_raspberrypi.display import *
```suggestion
from actfw_raspberrypi.display import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-raspberrypi instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/edid/__init__.py
> +from actfw_raspberrypi.edid import *
```suggestion
from actfw_raspberrypi.edid import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-raspberrypi instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/__init__.py
> +from actfw_core.task import *
```suggestion
from actfw_core.task import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/consumer/__init__.py
> +from actfw_core.task.consumer import *
```suggestion
from actfw_core.task.consumer import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/isolated/__init__.py
> +from actfw_core.task.isolated import *
```suggestion
from actfw_core.task.isolated import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/pipe/__init__.py
> +from actfw_core.task.pipe import *
```suggestion
from actfw_core.task.pipe import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/producer/__init__.py
> +from actfw_core.task.producer import *
```suggestion
from actfw_core.task.producer import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/task/task/__init__.py
> +from actfw_core.task.task import *
```suggestion
from actfw_core.task.task import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/v4l2/__init__.py
> +from actfw_core.v4l2 import *
```suggestion
from actfw_core.v4l2 import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/v4l2/control/__init__.py
> +from actfw_core.v4l2.control import *
```suggestion
from actfw_core.v4l2.control import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/v4l2/types/__init__.py
> +from actfw_core.v4l2.types import *
```suggestion
from actfw_core.v4l2.types import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-21 01:54 UTC, notogawa commented on actfw/v4l2/video/__init__.py
> +from actfw_core.v4l2.video import *
```suggestion
from actfw_core.v4l2.video import *
from warnings import warn
warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
```

2020-12-22 00:42 UTC, notogawa requested changes

2020-12-22 00:42 UTC, notogawa commented on actfw/task/consumer/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
dup

2020-12-22 00:42 UTC, notogawa commented on actfw/task/isolated/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
dup

2020-12-22 00:42 UTC, notogawa commented on actfw/task/pipe/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
dup

2020-12-22 03:22 UTC, laysakura commented on actfw/task/consumer/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
😭 ef2ea29

2020-12-22 03:22 UTC, laysakura commented on actfw/task/isolated/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
ef2ea29

2020-12-22 03:22 UTC, laysakura commented on actfw/task/pipe/__init__.py
> +warn(DeprecationWarning("actfw is DEPRECATED. Use actfw-core instead"))
ef2ea29

2020-12-22 03:23 UTC, notogawa submitted a review, later dismissed
LGTM

2020-12-22 03:27 UTC, laysakura commented
Thanks.
I will merge this PR after:

- @laysakura Upload release version of actfw-core and actfw-raspberrypi to PyPI after code review.
- @laysakura rerun CI (currently CI fails because actfw-{core,raspberrypi} are pre-release version and cannot install without --pre option.

2021-01-29 06:29 UTC, laysakura commented
>  @laysakura Upload actfw v1.4.0a1 to TestPyPI after code review.
>  @laysakura Test forward compatibility with some Actcast applications.
>     using actcast-app-idein-imagenet-classification (private)

finished.

I'm checking CI fail.

2021-01-29 06:47 UTC, laysakura commented
> ======================================================================
> ERROR: test_import.test_import_actfw_forward_compatibility:325
> {'from': 'actfw.v4l2.video', 'import': 'macholib'}
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/project/actfw/test/test_import.py", line 379, in test_import_actfw_forward_compatibility
>     exec(f'''from {param['from']} import {param['import']}''')
>   File "<string>", line 1, in <module>
> ImportError: cannot import name 'macholib' from 'actfw.v4l2.video' (/root/project/actfw/v4l2/video/__init__.py)

Seemingly because 

1. `ctypes.matcholib` existed in ctypes when I generate test parameters in `test/test_import.py` but
2. `ctypes.matcholib` has been removed in current ctypes.

The point is we don't have to assure import `cytpes` objects from `actfw.**` path.

I will change test parameters to only include Constants we ourselves define in actfw_core package.

2021-01-29 07:00 UTC, laysakura commented
@notogawa Please make your review again from this comment: https://github.com/Idein/actcast-app-python/pull/40#issuecomment-769607539

2021-01-29 07:19 UTC, notogawa reviewed
Importing tests for symbols in https://github.com/Idein/actfw-core/blob/master/actfw_core/v4l2/control.py and https://github.com/Idein/actfw-core/blob/master/actfw_core/v4l2/types.py are deleted at https://github.com/Idein/actcast-app-python/pull/40/commits/26d312d55f4186f3f48c3f276fe339a438e50073.

Is this what you intended?

2021-01-29 07:22 UTC, laysakura commented
ah, actually no 😰 

I should allow importing symbols in `video.py` added by:

```python
from actfw_core.v4l2.types import *
from actfw_core.v4l2.control import *
```

2021-02-01 04:08 UTC, laysakura commented
@notogawa added 7710ef2

2021-02-01 04:14 UTC, notogawa approved these changes
LGTM

2021-02-01 04:15 UTC, merged